eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/stz-git/springcloud_sell_config.git
          search-paths: config_repo
          basedir: E:\work\IdeaProjects\springcloud_sell\config\local_repository\
server:
  port: 8888

### to exposure "/bus-refresh" to update global configFile
management:
  endpoints:
    web:
      exposure:
        include: "*"


