eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:stz-git/springcloud_sell.git

server:
  port: 8084
