server:
  port: 8762

spring:
  application:
    name: eureka
  profiles: eureka2

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
  server:
    enable-self-preservation: false